smoke test for backend and frontend configured-error fixed07

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -396,52 +396,96 @@ jobs:
         - destroy-environment
         - revert-migrations
 
-
-
-  smoke-test:
+  
+  smoke-test-backend:
     docker:
-        # Docker image here that supports Ansible
-        - image: cimg/base:stable
+      - image: python:3.7-alpine3.11
     steps:
-        # Checkout code from git
-        - checkout
-       
-        - install_awscli
-        - install_nodejs  
-        - run:
-            name: Get backend Smoke test
-            command: |
-                 BACKEND_IP=$(aws ec2 describe-instances \
-                  --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                  --output text
-                  )
-                  export API_URL="http://${BACKEND_IP}:3030"
-                  echo ${BACKEND_IP}:3030
-                  echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-                  echo "${API_URL}"
-                  if curl -s ${API_URL}/api/status | grep "ok"
-                  then
-                     return 0
-                  else
-                     return 1
-                  fi
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl
+            pip install awscli
+      - run:
+          name: Backend smoke test
+          command: |
+             BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+             API_URL="http://${BACKEND_IP}:3030"
+             curl "${API_URL}/api/status"
 
-        - run:
-            name: Frontend smoke test.
-            command: |
-              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"            
-              echo ${URL} 
-              if curl -s ${URL} | grep "Welcome"
-              then
-                  # Change this to 0 after the job fails
-                exit 1
-              else
-                exit 1
-              fi
+  smoke-test-frontend:
+    docker:
+      - image: python:3.7-alpine3.11
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update curl
+            pip install awscli
+      - run:
+          name: Smoke test for front end
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi           
+
+
+
+  # smoke-test:
+  #   docker:
+  #       # Docker image here that supports Ansible
+  #       - image: cimg/base:stable
+  #   steps:
+  #       # Checkout code from git
+  #       - checkout
+       
+  #       - install_awscli
+  #       - install_nodejs  
+  #       - run:
+  #           name: Get backend Smoke test
+  #           command: |
+  #                BACKEND_IP=$(aws ec2 describe-instances \
+  #                 --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+  #                 --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #                 --output text
+  #                 )
+  #                 export API_URL="http://${BACKEND_IP}:3030"
+  #                 echo ${BACKEND_IP}:3030
+  #                 echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+  #                 echo "${API_URL}"
+  #                 if curl -s ${API_URL}/api/status | grep "ok"
+  #                 then
+  #                    return 0
+  #                 else
+  #                    return 1
+  #                 fi
+
+  #       - run:
+  #           name: Frontend smoke test.
+  #           command: |
+  #             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"            
+  #             echo ${URL} 
+  #             if curl -s ${URL} | grep "Welcome"
+  #             then
+  #                 # Change this to 0 after the job fails
+  #               exit 1
+  #             else
+  #               exit 1
+  #             fi
    
-        - destroy-environment  
-        - revert-migrations
+        # - destroy-environment  
+        # - revert-migrations
                   
 
 #   cloudfront-update:
@@ -458,6 +502,30 @@ jobs:
 #           command: |
 #             # your code here
 #       # Here's where you will add some code to rollback on failure  
+
+# cloudfront-update:
+#     docker:
+#       - image: cimg/base:2021.04
+#     steps:
+#       - checkout
+#       - dependencies
+#       - run:
+#           name: get old workflow for clean
+#           command: |
+#             OldWorkflowID=$(aws cloudformation \
+#             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+#             --no-paginate --output text)
+#             curl https://kvdb.io/RbTkSyUa7aVZkbXqr8rksx//migration_${CIRCLE_WORKFLOW_ID:0:7} \
+#             -H "X-Api-Key: ${THISDB_API_KEY}" \
+#             -d "$OldWorkflowID"  
+#       - run:
+#           name: Updating cloudfront distribution
+#           command: |
+#             aws cloudformation deploy \
+#             --template-file .circleci/files/cloudfront.yml \
+#             --stack-name InitialStack \
+#             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#             --tags project=udapeople
 
 # cleanup:
 #     docker:
