smoke test for backend and frontend configured

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -398,28 +398,51 @@ jobs:
 
 
 
-  # smoke-test:
-  #   docker:
-  #     # Lightweight Docker image 
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Backend smoke test.
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Frontend smoke test.
-  #         command: |
-  #           # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+        # Docker image here that supports Ansible
+        - image: cimg/base:stable
+    steps:
+        # Checkout code from git
+        - checkout
+       
+        - install_awscli
+        - install_nodejs  
+        - run:
+            name: Get backend Smoke test
+            command: |
+                 BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                  --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                  --filter Name=tag:Name,Values=backend-${CRICLE_WORKFLOW_ID:0:7} \
+                  --output text
+                  )
+                  export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+                  echo ${BACKEND_PUBLIC_IP}:3030
+                  echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+                  echo "API_URL = ${API_URL}"
+                  if curl "${API_URL}/api/status" | grep "ok"
+                  then
+                     return 0
+                  else
+                     return 1
+                  fi
+
+        - run:
+            name: Frontend smoke test.
+            command: |
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-${AWS_DEFAULT_REGION}.amazonaws.com/#/employees"            
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+                  # Change this to 0 after the job fails
+                exit 0
+              else
+                exit 1
+              fi
+   
+        - destroy-environment  
+        - revert-migrations
+                  
 
 #   cloudfront-update:
 #     docker:
@@ -484,8 +507,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
